# Generated by Django 3.1.7 on 2021-03-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_of_child', models.IntegerField()),
                ('nature_feeding', models.TextField()),
                ('artificial_feeding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=90)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('F', 'Kobieta'), ('M', 'Mężczyzna')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age_of_child', models.IntegerField(default=12)),
                ('ingredients', models.TextField(null=True)),
                ('preparation', models.TextField()),
                ('allergens', models.IntegerField(choices=[(1, 'bez laktozy'), (2, 'bez glutenu'), (3, 'bez orzechów'), (4, 'bez żółtka')])),
                ('favorite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_vaccine', models.CharField(max_length=80, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'Obowiązkowe'), (2, 'Wybrane_zalecane')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_vaccination', models.DateField()),
                ('additional', models.TextField(null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_for_you.person')),
                ('vaccine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_for_you.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='vaccine',
            field=models.ManyToManyField(through='memo_for_you.Vaccination', to='memo_for_you.Vaccine'),
        ),
        migrations.CreateModel(
            name='MedicalClinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_clinic', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('doctor', models.CharField(max_length=255)),
                ('date_of_visit', models.DateField()),
                ('reason', models.CharField(max_length=50)),
                ('description_of_reason', models.TextField()),
                ('treatment', models.TextField()),
                ('recommendation', models.TextField(null=True)),
                ('additional', models.TextField(null=True)),
                ('person_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_for_you.person')),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_hospital', models.CharField(max_length=255)),
                ('date_of_entry', models.DateField()),
                ('date_of_living', models.DateField(null=True)),
                ('reason', models.CharField(max_length=50)),
                ('description_of_reason', models.TextField()),
                ('treatment', models.TextField()),
                ('recommendation', models.TextField(null=True)),
                ('additional', models.TextField(null=True)),
                ('person_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_for_you.person')),
            ],
        ),
        migrations.CreateModel(
            name='ChildDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('height', models.IntegerField()),
                ('head_circuit', models.IntegerField(null=True)),
                ('additional_information', models.TextField(null=True)),
                ('person_full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo_for_you.person')),
            ],
        ),
    ]
