# Generated by Django 3.1.7 on 2021-03-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.CharField(default='brak opisu', max_length=255),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='recommended_age',
            field=models.CharField(default='wg tabeli', max_length=255),
        ),
    ]
