# Generated by Django 3.1.7 on 2021-03-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0002_auto_20210316_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdevelopment',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
