# Generated by Django 3.1.7 on 2021-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0004_auto_20210318_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdevelopment',
            name='date_of_entry',
            field=models.DateField(),
        ),
    ]
