# Generated by Django 3.1.7 on 2021-03-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0006_auto_20210318_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdevelopment',
            name='head_circuit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='childdevelopment',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='childdevelopment',
            name='weight',
            field=models.FloatField(),
        ),
    ]
