# Generated by Django 3.1.7 on 2021-03-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0007_auto_20210318_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='vaccine',
            new_name='vaccines',
        ),
    ]
