# Generated by Django 3.1.7 on 2021-03-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo_for_you', '0008_auto_20210324_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childdevelopment',
            old_name='person_full_name',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergens',
            field=models.IntegerField(choices=[(1, 'bez laktozy'), (2, 'bez glutenu'), (3, 'bez orzechów'), (4, 'bez żółtka'), (5, 'bez żółtka')]),
        ),
    ]
